### ISSUE TITLE
Homepage gets exported twice

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/laravel-export#12]
I think this might be an issue in spatie/crawler.

`http://localhost` and ``http://localhost/` are both crawled for some reason. The first should suffice.

**Comment by pepijn-de-wachter** [comment]
Hi,
I cannot seem tof figure out how to reproduce this, made a brand new laravel app with 2 extra pages linked from the default welcome blade,
added a logger in CollectionCrawlQueue::hasAlreadyBeenProcessed() (spatie/crawler) which theroretically gets executed for every url the crawler finds.
log output:
[2019-03-27 20:10:56] local.DEBUG: http://localhost/  
[2019-03-27 20:10:56] local.DEBUG: http://localhost/home  
[2019-03-27 20:10:56] local.DEBUG: http://localhost/test  
I also don't see any unexpected results in the dist folder.
Could you perhaps share a repository where this behaviour is noticed and in what way it visualizes?
Possibly os related? (I'm on the sometimes inferior Windows platform)
Kind regards

**Comment by sebastiandedeyne** [comment]
First of all, thanks for looking into this!

I was testing on a seperate branch of my personal site: https://github.com/sebastiandedeyne/sebastiandedeyne.com/tree/laravel-export

When I run `php artisan export -v`, this is what the output looks like:

```
Starting export...
[http://localhost/]
/ => /index.html
 => /index.html
/about => /about/index.html
/feed => /feed/index.html
/the-great-divide => /the-great-divide/index.html
/an-introduction-to-phoenix-liveview => /an-introduction-to-phoenix-liveview/index.html
/not-all-code-is-the-same => /not-all-code-is-the-same/index.html
/hindsight-2018-edition => /hindsight-2018-edition/index.html
/everyone-has-javascript-right => /everyone-has-javascript-right/index.html
/ia-writer-52-will-embrace-variable-fonts => /ia-writer-52-will-embrace-variable-fonts/index.html
...
```

The first and second page are the same.

We might do some changes regarding `entries` in this package later today (we're gonna try to get rid of the necessary `localhost` prefix internally), so this might take care of itself then...

**Comment by pepijn-de-wachter** [comment]
I see, if the problem persists I might be able to look into it this weekend.
Yesterday however after I shutdown my pc I though it could maybe the case
that in / you have a link to '/' but without the actual '/' meaning the
crawler picks it up as an extra uri, although in that specific case the
ltrim method should notice that now that I think about it.
Anyways, hopefully todays changes fix it, if they don't, I'll try to take a
look this weekend.

**Comment by sebastiandedeyne** [comment]
Update: the bug appears to only occur with our `InternalClient` Guzzle extension. We'll follow this up in #16.
