### ISSUE TITLE
Issue with . in route name ?

### ISSUE THREAD

**Issue by stefanzweifel** [spatie/laravel-export#13]
Currently working on an app which has version numbers in it's URLs. When running `php artisan export` these routes are not correctly recognized and no `index.html` files are generated.

**Works :)**
https://laravel-download-statistics-4a844a.netlify.com/downloads/by-month/2019-03/

**Fails :(**
https://laravel-download-statistics-4a844a.netlify.com/downloads/by-version/v5.8

![image](https://user-images.githubusercontent.com/1080923/55352514-4f750080-54c1-11e9-8f7e-aaf0cbd2e4ca.png)

Might this be related with #10 ? Maybe the export command should check against a list of common file-types?

**Comment by sebastiandedeyne** [comment]
Sounds good to do a better kind of detenction for file types 👍

**Comment by stefanzweifel** [comment]
Great. Will look into this more and send a PR if I found a good solution.

**Comment by SL0wZEr** [comment]
What about fixing this with a simple regular expression? excluding any "version" like paths.

```
$isFile = isset(explode('.', $url->getPath())[1]) && ! preg_match('/(.+\.[0-9])/', $url->getPath());
```

**Comment by stefanzweifel** [comment]
@SL0wZEr both of your ideas worked great for me. Do you want to create the PR for this? 😄

**Comment by SL0wZEr** [comment]
@stefanzweifel would love to. I'll send a PR tonight :)

**Comment by sebastiandedeyne** [comment]
Thanks!
