### ISSUE TITLE
Netlify custom 404

### ISSUE THREAD

**Issue by robbinworks** [spatie/laravel-export#15]
👋 Hey! 

First of all, thanks for this package! Great work! 🔥 

How would you go about generating a custom `404.html` for use with Netlify?

I'd prefer if this 404 page would inherit the default app layout just like any other page, preferably using my custom laravel `errors/404.blade.php` file.

From my understanding, if I want a custom 404 page instead of Netlify's default 404 page I'd have to create a `404.html` in the root of my build directory. ([source](https://www.netlify.com/docs/redirects/#custom-404))

Any suggestions?

**Comment by morpheus7CS** [comment]
Hey @robbinworks,

I quickly read through the Netlify docs. You indeed need a 404.html in your directory root. If you're wondering how to generate a 404 to deploy it, I'd go with defining a route just for this purpose in your web.php file:

`Route::view('/asdf', '404Error');

Hope that helps!
g

**Comment by robbinworks** [comment]
Thanks for your feedback!

That doesn't really solve my issue unfortunately, as it renders the following file: `/dist/404/index.html`. 

For netlify to pick it up as a custom 404 page it will need to be directly under my publish folder with a different name like so: `/dist/404.html`.

Am I missing something here?

**Comment by morpheus7CS** [comment]
Hey,

you can manualy move the index one folder up, from 404 folder to dist folder and rename it to 404.html. 

In this instance, Laravel Export just handles generating the html version of 404 for you.

Kind regards,
g

**Comment by robbinworks** [comment]
Thank you for your feedback!

I understand, I'll go with either that approach or maybe I'll just add a static 404.html in my public directory so that it will be generated in the export.

If I may, I'd like to raise a feature request for this kind of behavior, maybe we could pass it in the export config file? For reference, @JigsawByTighten has support for something similar:

https://jigsaw.tighten.co/docs/custom-404-page/

Thanks again for this package! 🙏

**Comment by sebastiandedeyne** [comment]
I'd like to have a solution for this, but not sure what 😅 

Open for suggestions!

**Comment by sebastiandedeyne** [comment]
Apparently you can override the default 404 page on Netlify, see https://blog.kiprosh.com/show-custom-404-error-page-for-netlify-applications/

**Comment by Gummibeer** [comment]
#31 should solve this. After it you can add `404.html` to your paths and it will generate a 404.html file. You can add a route for it or let your exception handler handle it.
