### ISSUE TITLE
How can this package be used with images from storage

### ISSUE THREAD

**Issue by bomshteyn** [spatie/laravel-export#18]
Since the storage directory is not included in the dist folder. How can you make this work if you have images stored there?

**Comment by sebastiandedeyne** [comment]
You need to add them to the `include` configuration:

https://github.com/spatie/laravel-export/blob/0fae3a05312cc8662d5af7705c26549c05d5adab/config/export.php#L21-L26

```
'include' => [
    ['source' => 'public', 'target' => ''],
    ['source' => 'storage/images', 'target' => 'images'],
]
```
