### ISSUE TITLE
Homepage URL return localhost

### ISSUE THREAD

**Issue by nemergut** [spatie/laravel-export#19]
Hi,
I have problem with correct exporting URLs, routes. 
The package render `url('/')` or `route('homepage')` to `http://localhost`. No matter what value is in `APP_URL`.

**Comment by nemergut** [comment]
It see that problem is on `spatie/laravel-export/src/Exporter.php:40`.

```php
$this->entries = array_map(function (string $entry) {
    return "http://localhost{$entry}";
}, $entries);
```

I tried replace it with `url()` function and now it work fine.

```php
$this->entries = array_map(function (string $entry) {
    return url($entry);
}, $entries);
```

**Comment by atymic** [comment]
Came across this issue to. Can you create a PR?

**Comment by freekmurze** [comment]
Fixed
