### ISSUE TITLE
[Feature] limit the pages to export to a specific list

### ISSUE THREAD

**Issue by Gummibeer** [spatie/laravel-export#26]
It would be great to be able to configure a specific list of pages that have o be exported and disable the crawler in this case.
Or a simpler solution: use the already available `entries` config key and add a `crawl_pages` boolean config key.

**Comment by sebastiandedeyne** [comment]
The crawler is going to be completely removed soon (it's too slow that way). We could add a way to filter pages then too 👍 

What's your exact use case? Why would you only want to export _some_ pages?

**Comment by Gummibeer** [comment]
The use case is a "mixed" page where some pages are static and some can't get static because of dynamic variables which change quite often.

**Comment by watercayman** [comment]
This would be nice for building separate trees to export into disparate auth levels on a static server.  IE run the service a few times to create different silos of the application.  I can the have the people standing up the static server only allow users with permission into those specific silos to have access to that folder.

So if I have a few pages related to clients, and a few pages for vendors, and some for applications... I can separate these out into different folders to make the static site easier to maintain permissions.

**Comment by sebastiandedeyne** [comment]
Solved with the new `paths` option :)
