### ISSUE TITLE
Set environment variables or config on export

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/laravel-export#27]
We need a way to set the app's environment and debug settings during the export. A generic way to modify config could be useful.

**Comment by justenh** [comment]
Our use case for this is needing to change our `ASSETS_URL` env value on export.

My first approach was to see if there was anything during  `AppServiceProvider->boot()` that would indicate that the site is being crawled, or if it was a typical request, but I didn't see any flag on `Spatie\Export\Exporter` indicating that. 

Something like this?
```
public function boot(Exporter $exporter)
{
  // Check to see if the app is being exported
  if ($exporter->isExporting) {
     config('app.asset_url, 'path-to-assets');
  }
}
```

In the meantime, I have wrapped our export command to backup the current .env file, and then replace it with a different .env file (.env.export). Once the export is completed (or fails), the backed up .env file is renamed again and set to be the app's primary .env file. Would love to know the right way to accomplish this.

**Comment by Gummibeer** [comment]
I use the default and super easy approach laravel provides for artisan commands
```bash
php artisan export --env=prod
```

**Comment by sebastiandedeyne** [comment]
That's a very good point, I'm closing this then!

**Comment by justenh** [comment]
> I use the default and super easy approach laravel provides for artisan commands
> 
> ```shell
> php artisan export --env=prod
> ```
> 
> So I don't see any reason to add something in this package. Only add this to the docs. You can also create your own env netlify, zwei.now or whatever. And keep an environment aware env file in your folder `.env.prod`

Thanks @Gummibeer. That's the perfect solution! I must have missed this in the Laravel docs!
