### ISSUE TITLE
Exclude mix-manifest.json by default

### ISSUE THREAD

**Issue by royvanv** [spatie/laravel-export#33]
The file mix-manifest.json serves no more purpose after the assets are compiled by Laravel Mix.

Unless there's a good reason why it's not excluded, I think the file should be added to the config option `exclude_file_patterns` in the default configuration for this package.

**Comment by sebastiandedeyne** [comment]
That makes sense! Care to send over a PR?

**Comment by royvanv** [comment]
Yes, please review PR #34.
