### ISSUE TITLE
CircleCI - Export Crawl Not Working

### ISSUE THREAD

**Issue by MPJHorner** [spatie/laravel-export#35]
Locally this runs fine.
I run this on my circleci environment 

`- run:
                name: Generate Site
                command: cd src && php artisan export   `

I know its run because;

1. It correctly copies the public dir stuff.
2. it correctly exports the stuff that isn't crawlable (that I configured) such as sitemap.xml

It does not generate any errors.

My config is as follows:
`<?php

return [

    /*
     * If true, the exporter will crawl through your site's pages to determine
     * the paths that need to be exported.
     */
    'crawl' => true,

    /*
     * Add additional paths to be added to the export here. If you're using the
     * `crawl` option, you probably don't need to add anything here.
     *
     * For example: "about", "posts/featured"
     */
    'paths' => [
        'sitemap.xml',
        'robots.txt'
    ],

    /*
     * Files and folders that should be included in the build. Expects
     * key/value pairs with current paths as keys, and destination paths
     * as values.
     *
     * By default your `public` folder's contents will be added to the export.
     */
    'include_files' => [
        'public' => '',
    ],

    /*
     * File patterns that should be excluded from the included files.
     */
    'exclude_file_patterns' => [
        '/\.php$/',
        '/mix-manifest\.json$/',
    ],

    /*
     * Whether or not the destination folder should be emptied before starting
     * the export.
     */
    'clean_before_export' => true,

    /*
     * If set, the site will be exported to this disk. Disks can be configured
     * in `config/filesystems.php`.
     *
     * If empty, your site will be exported to a `dist` folder.
     */
    'disk' => null,

    /*
     * Shell commands that should be run before the export starts when running
     * `php artisan export`.
     *
     * You can skip these by adding a `--skip-{name}` flag to the command.
     */
    'before' => [
        // 'assets' => '/usr/local/bin/yarn production',
    ],

    /*
     * Shell commands that should be run after the export has finished when
     * running `php artisan export`.
     *
     * You can skip these by adding a `--skip-{name}` flag to the command.
     */
    'after' => [
        // 'deploy' => '/usr/local/bin/netlify deploy --prod',
    ],

];
`

I'm running composer etc so I would expect everything needed to be available to crawl. What does the crawl feature actually do? Thanks!

**Comment by MPJHorner** [comment]
I couldn't get to the bottom of why _crawl_ wasn't working. Given it wasn't giving any errors.
I decided to go through the process of manually adding in my routes in a loop.
However, you don't access to routes in AppServiceProvider (as this is bootstraping before routes are loading). While you can wait for them to be loaded you then can't use Route /w params.

This in mind I added an override command like below;

`<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Artisan;
use Spatie\Export\Exporter;
use App\SitemapHelper;
class ExportToStaticSite extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'export:static';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'OVerride command to export site to static site.';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle(Exporter $exporter)
    {
        $exporter->crawl(false);
        $sitemap = new SitemapHelper();
        $sitemap->generate();
        $exporter->paths($sitemap->getRoutesArray());
        Artisan::call('export');
    }
}
`

Sitemap already had all the routes so easiest way to export it.

**Comment by sebastiandedeyne** [comment]
When the crawl doesn't work, is an `index.html` generated in the dist folder? Or absolutely nothing besides the additional files.
