### ISSUE TITLE
The "--skip-deploy" option does not exist. 

### ISSUE THREAD

**Issue by djunehor** [spatie/laravel-export#56]
After following the installation guide on the readme.md, I ran `php artisan export --skip-deploy` and got the response `The "--skip-deploy" option does not exist. `.

I'm not sure what I'm doing wrong.

Config
php 7.2
Laravel 6.18

**Comment by sebastiandedeyne** [comment]
The `--skip-XXX` commands are dynamically generated based on the `before` and `after` hooks set up in your config.

For example, if you set up an `assets` step in your `before` hooks, `--skip-assets` would be available.

```php
return [
    'before' => [
        'assets' => '/usr/local/bin/yarn production',
    ],
];
```
