### ISSUE TITLE
Rework before and after hooks configuration

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/laravel-export#8]
Right now you define an array of before and after hooks. With the CLI you can either skip all before or all after hooks, it would be nice to have more granular control here.

Option A)

Keep the config mostly the same, but suport associative arrays to label hooks.

```php
return [
    'before' => [
        'assets' => '/usr/local/bin/yarn production',
        'slack' => 'php artisan slack:message "Starting export"',
    ],
];
```

Then you could skip specific hooks instead of all hooks.

```php
php artisan export --skip-before=slack
```

Option B)

We could combine before and after hooks to a single `hooks` array that accepts configuration arrays instead of plain strings.

```php
return [
    'hooks' => [
        'assets' => ['command' => '/usr/local/bin/yarn production', 'run' => 'before'],
    ],
];
```

Or

```php
return [
    'hooks' => [
        'assets' => ['before' => '/usr/local/bin/yarn production'],
    ],
];
```

---

I'm leaning towards the second example of option B because it reads nicely and adds the most flexibility.

**Comment by freekmurze** [comment]
On first thought I like option A the best because it forces you to group `before` and `after`. It also reads/scans nicely. You could add a `hooks` top level key.

```
return [
    'hooks' => [
        'before' => [
            'slack' => 'php artisan slack:message "Paolo asks for order"',
        ],
        'after' => [
            'slack' => 'php artisan slack:message "Enzo prepares Pizza Royale"',
        ],
    ],
];
```

Option B could get messy when you mix `before` and `after`.

```php
return [
    'hooks' => [
        'assets' => ['before' => '/usr/local/bin/yarn production'],
        'another' => ['after' => '/usr/local/bin/enzo'],
        'yetAnother' => ['before' => '/usr/local/bin/paolo'],
    ],
];
```

**Comment by sebastiandedeyne** [comment]
The way I see is is that I don't really care _when_ a hook will be run, that's kind of an implementation detail to me. Option B shows at a glance _which_ hooks there are. It also makes it easier if we want to add other hooks than before/after in the future.

**Comment by freekmurze** [comment]
If you want to optimise figuring out which hooks there are and not when they should run, option B is indeed better.
